baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ret2sutd'
theme = 'hextra'
enableInlineShortcodes = true

[menus]
    [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 1
    identifier = 'about'

    [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 3

[markup.goldmark.renderer]
hardwraps = true


